version: "3.9"
services:
  db:
    image: symdit/postgresql15-bigm:latest
    restart: always
    container_name: integration-tests
    ports:
      - '5432:5432'
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
      PGDATA: /var/lib/postgresql/data/pgdata
