version: "3.9"
services:
  app:
    container_name: app
    image: nestjs-startkit:latest
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: database
    image: symdit/postgresql15-bigm:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
        test: ["CMD-SHELL", "pg_isready --username=prisma --dbname=tests"]
        interval: 10s
        timeout: 5s
        retries: 5