name: Delete Review Service CI

on:
  pull_request:
    types: [ closed ]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: "ap-northeast-1"
            aws-access-key-id: ${{ secrets.APPRUNNER_ACCESS_KEY_ID }} #アクセスキー
            aws-secret-access-key: ${{ secrets.APPRUNNER_ACCESS_SECRET_KEY }} #シークレットキー

        - name: Get Service Arn
          id: get-service-arn
          env:
            PR_NUMBER: ${{ github.event.number }}
          run: |
            until [ startsWith(`aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='nestjs-startkit_$PR_NUMBER'&&Status=='RUNNING']|[0].ServiceArn"`, arn:aws:apprunner)` ]; do
              sleep 30
            done
            SERVICE_ARN=`aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='nestjs-startkit_$PR_NUMBER'&&Status=='RUNNING']|[0].ServiceArn"`
            echo "service-arn=$SERVICE_ARN" >> $GITHUB_OUTPUT

        - name: Delete AppRunner Service
          if: ${{ steps.get-service-arn.outputs.service-arn }}
          run: |
            aws apprunner delete-service --service-arn ${{ steps.get-service-arn.outputs.service-arn }}
