name: Resume Review App

on:
  issue_comment:
    types: [created, edited]

jobs:
  resume-review-app:
    name: Resume Review App
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/resume') }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.APPRUNNER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.APPRUNNER_ACCESS_SECRET_KEY }}
        aws-region: "ap-northeast-1"

    - name: Check Service Exist
      id: check-service-exist
      env:
        PR_NUMBER: ${{ github.event.issue.number }}
      run: |
        SERVICE_NAME=`echo "nestjs-startkit_$PR_NUMBER" | cut -c 1-40 | sed -e "s/[^a-zA-Z0-9_-]/-/g"`
        SERVICE_ARN=`aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$SERVICE_NAME'&&Status=='PAUSED']|[0].ServiceArn"`
        echo "::set-output name=service-arn::$SERVICE_ARN"

    - name: Resume App Runner Service
      id: resume-service
      if: ${{ steps.check-service-exist.outputs.service-arn }}
      run: |
        aws apprunner resume-service --service-arn ${{ steps.check-service-exist.outputs.service-arn }}
